export const data = [
    {
        "_id":"1",
        "name":"Virtual Contest",
        "link":"/VirtualContest"
    },
    {
        "_id":"2",
        "name":"Compare",
        "link":"/Compare"
    },
    {
        "_id":"3",
        "name":"Ladder",
        "link":"/Ladder"
    },
    {
        "_id":"4",
        "name":"Upsolver",
        "link":"/Upsolver"
    },
    {
        "_id":"5",
        "name":"Vizualizer",
        "link":"/Vizualizer"
    },
    {
        "_id":"6",
        "name":"Recommender",
        "link":"/Recommender"
    } 
 ];
